spring.datasource.url=jdbc:postgresql://localhost:5432/department_db
spring.datasource.username = postgres
spring.datasource.password = Example@2026#

#JPA properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#SQL Log queries
logging.level.org.hibernate.SQL= DEBUG

logging.level.org.hibernate.orm.jdbc.bind=TRACE

#Service Discovery - Eureka properties
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/


# Adding a property to test the /actuator/refresh to automatically updates 
# the latest changes without restarting the microservice everything when we make any
# change in the config file.
spring.boot.message = Hello, Department Service.!!!!!
