
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
spring.datasource.username=postgres
spring.datasource.password=Example@2026#

# Server port
server.port=8081

#Hibernate Queries
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Logging Queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#Actuator properties
management.endpoints.web.exposure.include=*

#Feign Log properties
logging.level.feign.Logger=DEBUG

# Replace with your actual package
logging.level.personal.projects.Employee_Service=DEBUG

spring.cloud.openfeign.client.config.default.loggerLevel=FULL

#Service Discovery - Eureka properties
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

#Actuator properties
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.group.readiness.include=*
management.endpoint.health.group.liveness.include=*

# Circuit Breaker configuration
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.register-health-indicator=true
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.sliding-window-size=10
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.sliding-window-type=COUNT_BASED

