
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
spring.datasource.username=postgres
spring.datasource.password=Example@2026#

# Server port
server.port=8081

#Hibernate Queries
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Logging Queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#Actuator properties
management.endpoints.web.exposure.include=*

#Feign Log properties
logging.level.feign.Logger=DEBUG

# Replace with your actual package
logging.level.personal.projects.Employee_Service=DEBUG

spring.cloud.openfeign.client.config.default.loggerLevel=FULL

#Service Discovery - Eureka properties
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
